CREATE TABLE User(
  Email VARCHAR(255) PRIMARY KEY,
  Password VARCHAR(64)
);

CREATE TABLE Habit(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255),
  Email VARCHAR(255),
  FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE HabitEntry(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  HabitId INT,
  EntryDate DATE NOT NULL,
  Status ENUM('Complete', 'Incomplete'),
  FOREIGN KEY (HabitID) REFERENCES Habit(Id) ON DELETE CASCADE
);

CREATE TABLE Metric(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(255),
  Email VARCHAR(255),
  FOREIGN KEY (Email) REFERENCES User(Email)
);

CREATE TABLE MetricEntry(
  Id INT AUTO_INCREMENT PRIMARY KEY,
  MetricId INT,
  EntryDate DATE NOT NULL,
  Value FLOAT,
  FOREIGN KEY (MetricId) REFERENCES Metric(Id) ON DELETE CASCADE
);
