services:
  # api:
    # build:
      # context: backend
    # ports:
      # - "3000:3000"
    # volumes:
      # - ./backend/src:/app/src
  mysql:
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
